"""Before 1st review migration

Revision ID: db85deb81643
Revises: fa9ed5812745
Create Date: 2023-03-05 15:29:22.358234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db85deb81643'
down_revision = 'fa9ed5812745'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
