"""Endpoints migration

Revision ID: fa9ed5812745
Revises: 56fc85ac019c
Create Date: 2023-03-05 15:25:19.262072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9ed5812745'
down_revision = '56fc85ac019c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
